[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
name = "kernel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.3.1"
regex = "1.7.1"
chrono = "0.4.22"
