[package]
name = "test-cli"
description = "Native playground for testing cworks kernel features"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel = { path = "../kernel" }
log = "0.4.17"
env_logger = "0.10.0"
wasmi = "1.1.0"
postcard = { version = "1", features = ["alloc"] }
# cworks-sdk = { path = "../sdk" }
# plugin-eval = { path = "../plugin-eval" }
cworks-lua = { path = "../cworks-lua" }
mlua = { version = "0.12", features = ["lua55", "vendored", "async", "macros"] }
