[package]
name = "test-cli"
description = "Native playground for testing cworks kernel features"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel = { path = "../kernel" }
log = "0.4.17"
env_logger = "0.10.0"
cworks-sdk = { path = "../sdk" }
wasmi = "1.1.0"
postcard = { version = "1", features = ["alloc"] }
plugin-eval = { path = "../plugin-eval" }
